import Foundation

// MARK: - Localized String Keys

enum L10n {
    static let languageKey = "prefs.language"


    /// Supported languages — names in native form
    static let supportedLanguages: [(code: String, name: String)] = [
        ("auto",   "跟随系统 / Follow System"),
        ("zh-Hans", "简体中文"),
        ("en",      "English"),
        ("zh-Hant", "繁體中文"),
        ("fr",      "Français"),
        ("ja",      "日本語"),
        ("de",      "Deutsch"),
        ("it",      "Italiano"),
        ("es",      "Español"),
        ("pt",      "Português"),
        ("id",      "Bahasa Indonesia"),
        ("ru",      "Русский"),
    ]

    static func tr(_ key: String) -> String {
        currentDict[canonicalKey(key)] ?? key
    }

    /// Returns the active dictionary based on user preference or system locale
    static var currentDict: [String: String] {
        let code = selectedLanguage
        if code == "auto" {
            return autoDetected
        }
        return dictFor(code)
    }

    private static var autoDetected: [String: String] {
        let lang = Locale.preferredLanguages.first ?? "zh-Hans"
        return dictFor(lang)
    }

    private static func dictFor(_ identifier: String) -> [String: String] {
        let prefix = langPrefix(identifier)
        switch prefix {
        case "en":       return en
        case "zh-Hant":  return zhHant
        case "fr":       return fr
        case "ja":       return ja
        case "de":       return de
        case "it":       return it
        case "es":       return es
        case "pt":       return pt
        case "id":       return id
        case "ru":       return ru
        default:         return zhHans
        }
    }

    /// Language code from UserDefaults; "auto" means follow system
    static var selectedLanguage: String {
        UserDefaults.standard.string(forKey: languageKey) ?? "auto"
    }

    static func setLanguage(_ code: String) {
        UserDefaults.standard.set(code, forKey: languageKey)
    }

    private static func langPrefix(_ identifier: String) -> String {
        if identifier.hasPrefix("zh-Hant") || identifier.hasPrefix("zh-HK") || identifier.hasPrefix("zh-TW") { return "zh-Hant" }
        if identifier.hasPrefix("zh") { return "zh-Hans" }
        return String(identifier.prefix(2))
    }

    private static func canonicalKey(_ key: String) -> String {
        key.lowercased().trimmingCharacters(in: .whitespaces)
    }

    // MARK: - Translations

    /// Simplified Chinese (default)
    static let zhHans: [String: String] = [
        "preferences": "偏好设置",
        "quit": "退出",
        "ready": "准备开始",
        "focus_round": "专注 · 第 %d 个番茄",
        "short_break": "短休息",
        "long_break": "长休息",
        "focus_paused": "专注已暂停",
        "break_paused": "休息已暂停",
        "start": "开始",
        "continue": "继续",
        "pause": "暂停",
        "skip": "跳过",
        "today": "今日",
        "pomodoros_count": "%d 个番茄",
        "total_focus": "总专注",
        "seconds_unit": "秒",
        "minutes_unit": "分钟",
        "focus_complete_title": "专注完成!",
        "focus_complete_body": "辛苦了，休息一下吧",
        "break_complete_title": "休息结束",
        "break_complete_body": "准备好继续了吗？",
        "timer": "计时",
        "appearance": "外观",
        "notifications": "通知",
        "shortcuts": "快捷键",
        "focus_duration": "专注时长",
        "short_break_duration": "短休息时长",
        "long_break_duration": "长休息时长",
        "long_break_interval": "长休息间隔",
        "every_n_pomodoros": "每 %d 个番茄",
        "behavior": "行为",
        "auto_start_next": "自动开始下一阶段",
        "launch_at_login": "登录时自动启动",
        "menu_bar_display": "菜单栏显示",
        "display_mode": "显示模式",
        "time_only": "仅计时数字",
        "time_with_icon": "数字 + 图标",
        "example_time_only": "示例: 24:59",
        "example_time_icon": "示例: 🍅 25m",
        "notification_mode": "通知方式",
        "sound_banner": "声音 + 横幅",
        "sound_only": "仅声音",
        "banner_only": "仅横幅",
        "off": "关闭",
        "sound": "音效",
        "tick_enabled": "最后 60 秒 tick 音效",
        "tick_description": "倒计时最后 60 秒，每秒播放短促提示音",
        "tick_sound": "提示音",
        "global_shortcuts": "全局快捷键",
        "shortcut_toggle": "开始 / 暂停",
        "shortcut_skip": "跳过",
        "shortcut_reset": "重置",
        "accessibility_hint": "需要辅助功能权限才能使用全局快捷键。可在 系统设置 → 隐私与安全性 → 辅助功能 中授权。",
        "preferences_title": "番茄时钟 偏好设置",
        "language": "语言",
        "language_hint": "切换后界面即时生效",
        "mon": "一", "tue": "二", "wed": "三", "thu": "四", "fri": "五", "sat": "六", "sun": "日",
        "about": "关于",
    ]

    /// English
    static let en: [String: String] = [
        "preferences": "Preferences",
        "quit": "Quit",
        "ready": "Ready",
        "focus_round": "Focus · Pomodoro #%d",
        "short_break": "Short Break",
        "long_break": "Long Break",
        "focus_paused": "Focus Paused",
        "break_paused": "Break Paused",
        "start": "Start",
        "continue": "Continue",
        "pause": "Pause",
        "skip": "Skip",
        "today": "Today",
        "pomodoros_count": "%d pomodoros",
        "total_focus": "Total Focus",
        "seconds_unit": "s",
        "minutes_unit": "min",
        "focus_complete_title": "Focus Complete!",
        "focus_complete_body": "Great work! Take a break.",
        "break_complete_title": "Break Over",
        "break_complete_body": "Ready to focus again?",
        "timer": "Timer",
        "appearance": "Appearance",
        "notifications": "Notifications",
        "shortcuts": "Shortcuts",
        "focus_duration": "Focus Duration",
        "short_break_duration": "Short Break",
        "long_break_duration": "Long Break",
        "long_break_interval": "Long Break Interval",
        "every_n_pomodoros": "Every %d pomodoros",
        "behavior": "Behavior",
        "auto_start_next": "Auto-start next phase",
        "launch_at_login": "Launch at Login",
        "menu_bar_display": "Menu Bar Display",
        "display_mode": "Display Mode",
        "time_only": "Time Only",
        "time_with_icon": "Time + Icon",
        "example_time_only": "Example: 24:59",
        "example_time_icon": "Example: 🍅 25m",
        "notification_mode": "Notification Mode",
        "sound_banner": "Sound + Banner",
        "sound_only": "Sound Only",
        "banner_only": "Banner Only",
        "off": "Off",
        "sound": "Sound",
        "tick_enabled": "Last 60s Tick Sound",
        "tick_description": "Plays a short tick every second during the final minute of focus.",
        "tick_sound": "Tick Sound",
        "global_shortcuts": "Global Shortcuts",
        "shortcut_toggle": "Start / Pause",
        "shortcut_skip": "Skip",
        "shortcut_reset": "Reset",
        "accessibility_hint": "Global shortcuts require Accessibility permission. Grant it in System Settings → Privacy & Security → Accessibility.",
        "preferences_title": "PomodoroNotch Preferences",
        "language": "Language",
        "language_hint": "Changes take effect immediately.",
        "mon": "Mon", "tue": "Tue", "wed": "Wed", "thu": "Thu", "fri": "Fri", "sat": "Sat", "sun": "Sun",
        "about": "About",
    ]

    /// Traditional Chinese
    static let zhHant: [String: String] = [
        "preferences": "偏好設定",
        "quit": "退出",
        "ready": "準備開始",
        "focus_round": "專注 · 第 %d 個番茄",
        "short_break": "短休息",
        "long_break": "長休息",
        "focus_paused": "專注已暫停",
        "break_paused": "休息已暫停",
        "start": "開始",
        "continue": "繼續",
        "pause": "暫停",
        "skip": "跳過",
        "today": "今日",
        "pomodoros_count": "%d 個番茄",
        "total_focus": "總專注",
        "seconds_unit": "秒",
        "minutes_unit": "分鐘",
        "focus_complete_title": "專注完成！",
        "focus_complete_body": "辛苦了，休息一下吧",
        "break_complete_title": "休息結束",
        "break_complete_body": "準備好繼續了嗎？",
        "timer": "計時",
        "appearance": "外觀",
        "notifications": "通知",
        "shortcuts": "快速鍵",
        "focus_duration": "專注時長",
        "short_break_duration": "短休息時長",
        "long_break_duration": "長休息時長",
        "long_break_interval": "長休息間隔",
        "every_n_pomodoros": "每 %d 個番茄",
        "behavior": "行為",
        "auto_start_next": "自動開始下一階段",
        "launch_at_login": "登入時自動啟動",
        "menu_bar_display": "選單列顯示",
        "display_mode": "顯示模式",
        "time_only": "僅計時數字",
        "time_with_icon": "數字 + 圖示",
        "example_time_only": "範例: 24:59",
        "example_time_icon": "範例: 🍅 25m",
        "notification_mode": "通知方式",
        "sound_banner": "聲音 + 橫幅",
        "sound_only": "僅聲音",
        "banner_only": "僅橫幅",
        "off": "關閉",
        "sound": "音效",
        "tick_enabled": "最後 60 秒 tick 音效",
        "tick_description": "倒數最後 60 秒，每秒播放短促提示音",
        "tick_sound": "提示音",
        "global_shortcuts": "全域快速鍵",
        "shortcut_toggle": "開始 / 暫停",
        "shortcut_skip": "跳過",
        "shortcut_reset": "重設",
        "accessibility_hint": "需要輔助功能權限才能使用全域快速鍵。可在 系統設定 → 隱私與安全性 → 輔助功能 中授權。",
        "preferences_title": "番茄時鐘 偏好設定",
        "language": "語言",
        "language_hint": "切換後介面即時生效",
        "mon": "一", "tue": "二", "wed": "三", "thu": "四", "fri": "五", "sat": "六", "sun": "日",
        "about": "關於",
    ]

    /// French
    static let fr: [String: String] = [
        "preferences": "Préférences", "quit": "Quitter", "ready": "Prêt",
        "focus_round": "Focus · Pomodoro n°%d",
        "short_break": "Pause courte", "long_break": "Pause longue",
        "focus_paused": "Focus en pause", "break_paused": "Pause en pause",
        "start": "Démarrer", "continue": "Continuer", "pause": "Pause", "skip": "Passer",
        "today": "Aujourd'hui", "pomodoros_count": "%d pomodoros",
        "total_focus": "Focus total", "seconds_unit": "s", "minutes_unit": "min",
        "focus_complete_title": "Focus terminé !",
        "focus_complete_body": "Bon travail ! Prenez une pause.",
        "break_complete_title": "Pause terminée",
        "break_complete_body": "Prêt à vous concentrer ?",
        "timer": "Minuteur", "appearance": "Apparence",
        "notifications": "Notifications", "shortcuts": "Raccourcis",
        "focus_duration": "Durée de focus", "short_break_duration": "Pause courte",
        "long_break_duration": "Pause longue", "long_break_interval": "Intervalle pause longue",
        "every_n_pomodoros": "Tous les %d pomodoros", "behavior": "Comportement",
        "auto_start_next": "Démarrer automatiquement", "launch_at_login": "Lancer à l'ouverture",
        "menu_bar_display": "Affichage barre de menu", "display_mode": "Mode d'affichage",
        "time_only": "Temps seul", "time_with_icon": "Temps + Icône",
        "example_time_only": "Exemple : 24:59", "example_time_icon": "Exemple : 🍅 25m",
        "notification_mode": "Mode de notification",
        "sound_banner": "Son + Bannière", "sound_only": "Son seul",
        "banner_only": "Bannière seule", "off": "Désactivé",
        "sound": "Son", "tick_enabled": "Tic-tac des 60 dernières secondes",
        "tick_description": "Joue un tic-tac chaque seconde pendant la dernière minute de focus.",
        "tick_sound": "Son du tic-tac", "global_shortcuts": "Raccourcis globaux",
        "shortcut_toggle": "Démarrer / Pause", "shortcut_skip": "Passer", "shortcut_reset": "Réinitialiser",
        "accessibility_hint": "Les raccourcis globaux nécessitent l'autorisation d'accessibilité. Accordez-la dans Réglages Système → Confidentialité et sécurité → Accessibilité.",
        "preferences_title": "Préférences PomodoroNotch",
        "language": "Langue",
        "language_hint": "Les changements prennent effet immédiatement.",
        "mon": "Lun", "tue": "Mar", "wed": "Mer", "thu": "Jeu", "fri": "Ven", "sat": "Sam", "sun": "Dim",
        "about": "À propos",
    ]

    /// Japanese
    static let ja: [String: String] = [
        "preferences": "設定", "quit": "終了", "ready": "準備完了",
        "focus_round": "集中 · %d ポモドーロ",
        "short_break": "短い休憩", "long_break": "長い休憩",
        "focus_paused": "集中一時停止", "break_paused": "休憩一時停止",
        "start": "開始", "continue": "続行", "pause": "一時停止", "skip": "スキップ",
        "today": "今日", "pomodoros_count": "%d ポモドーロ",
        "total_focus": "合計集中時間", "seconds_unit": "秒", "minutes_unit": "分",
        "focus_complete_title": "集中完了！", "focus_complete_body": "お疲れ様です。休憩しましょう。",
        "break_complete_title": "休憩終了", "break_complete_body": "集中を再開する準備はできましたか？",
        "timer": "タイマー", "appearance": "外観", "notifications": "通知", "shortcuts": "ショートカット",
        "focus_duration": "集中時間", "short_break_duration": "短い休憩",
        "long_break_duration": "長い休憩", "long_break_interval": "長い休憩の間隔",
        "every_n_pomodoros": "%d ポモドーロごと", "behavior": "動作",
        "auto_start_next": "次のフェーズを自動開始", "launch_at_login": "ログイン時に起動",
        "menu_bar_display": "メニューバー表示", "display_mode": "表示モード",
        "time_only": "時間のみ", "time_with_icon": "時間 + アイコン",
        "example_time_only": "例: 24:59", "example_time_icon": "例: 🍅 25m",
        "notification_mode": "通知モード", "sound_banner": "サウンド + バナー",
        "sound_only": "サウンドのみ", "banner_only": "バナーのみ", "off": "オフ",
        "sound": "サウンド", "tick_enabled": "残り60秒のチック音",
        "tick_description": "集中の最後の1分間、毎秒短いチック音を再生します。",
        "tick_sound": "チック音", "global_shortcuts": "グローバルショートカット",
        "shortcut_toggle": "開始 / 一時停止", "shortcut_skip": "スキップ", "shortcut_reset": "リセット",
        "accessibility_hint": "グローバルショートカットにはアクセシビリティ許可が必要です。システム設定 → プライバシーとセキュリティ → アクセシビリティで許可してください。",
        "preferences_title": "PomodoroNotch 設定",
        "language": "言語",
        "language_hint": "変更はすぐに反映されます。",
        "mon": "月", "tue": "火", "wed": "水", "thu": "木", "fri": "金", "sat": "土", "sun": "日",
        "about": "概要",
    ]

    /// German
    static let de: [String: String] = [
        "preferences": "Einstellungen", "quit": "Beenden", "ready": "Bereit",
        "focus_round": "Fokus · Pomodoro Nr. %d",
        "short_break": "Kurze Pause", "long_break": "Lange Pause",
        "focus_paused": "Fokus pausiert", "break_paused": "Pause pausiert",
        "start": "Start", "continue": "Fortsetzen", "pause": "Pause", "skip": "Überspringen",
        "today": "Heute", "pomodoros_count": "%d Pomodoros",
        "total_focus": "Gesamtfokus", "seconds_unit": "s", "minutes_unit": "min",
        "focus_complete_title": "Fokus abgeschlossen!",
        "focus_complete_body": "Gute Arbeit! Machen Sie eine Pause.",
        "break_complete_title": "Pause vorbei",
        "break_complete_body": "Bereit, sich wieder zu konzentrieren?",
        "timer": "Timer", "appearance": "Erscheinungsbild",
        "notifications": "Benachrichtigungen", "shortcuts": "Tastenkürzel",
        "focus_duration": "Fokusdauer", "short_break_duration": "Kurze Pause",
        "long_break_duration": "Lange Pause", "long_break_interval": "Lange-Pause-Intervall",
        "every_n_pomodoros": "Alle %d Pomodoros", "behavior": "Verhalten",
        "auto_start_next": "Nächste Phase automatisch starten",
        "launch_at_login": "Beim Anmelden starten",
        "menu_bar_display": "Menüleistenanzeige", "display_mode": "Anzeigemodus",
        "time_only": "Nur Zeit", "time_with_icon": "Zeit + Symbol",
        "example_time_only": "Beispiel: 24:59", "example_time_icon": "Beispiel: 🍅 25m",
        "notification_mode": "Benachrichtigungsmodus",
        "sound_banner": "Ton + Banner", "sound_only": "Nur Ton",
        "banner_only": "Nur Banner", "off": "Aus",
        "sound": "Ton", "tick_enabled": "Tick-Geräusch (letzte 60s)",
        "tick_description": "Spielt in der letzten Fokus-Minute jede Sekunde ein kurzes Tick-Geräusch ab.",
        "tick_sound": "Tick-Geräusch", "global_shortcuts": "Globale Tastenkürzel",
        "shortcut_toggle": "Start / Pause", "shortcut_skip": "Überspringen",
        "shortcut_reset": "Zurücksetzen",
        "accessibility_hint": "Globale Tastenkürzel erfordern die Eingabehilfen-Berechtigung. Erteilen Sie diese in Systemeinstellungen → Datenschutz & Sicherheit → Eingabehilfen.",
        "preferences_title": "PomodoroNotch Einstellungen",
        "language": "Sprache",
        "language_hint": "Änderungen werden sofort wirksam.",
        "mon": "Mo", "tue": "Di", "wed": "Mi", "thu": "Do", "fri": "Fr", "sat": "Sa", "sun": "So",
        "about": "Über",
    ]

    /// Italian
    static let it: [String: String] = [
        "preferences": "Preferenze", "quit": "Esci", "ready": "Pronto",
        "focus_round": "Focus · Pomodoro n.%d",
        "short_break": "Pausa breve", "long_break": "Pausa lunga",
        "focus_paused": "Focus in pausa", "break_paused": "Pausa in pausa",
        "start": "Avvia", "continue": "Continua", "pause": "Pausa", "skip": "Salta",
        "today": "Oggi", "pomodoros_count": "%d pomodori",
        "total_focus": "Focus totale", "seconds_unit": "s", "minutes_unit": "min",
        "focus_complete_title": "Focus completato!",
        "focus_complete_body": "Ottimo lavoro! Fai una pausa.",
        "break_complete_title": "Pausa finita",
        "break_complete_body": "Pronto a concentrarti di nuovo?",
        "timer": "Timer", "appearance": "Aspetto", "notifications": "Notifiche",
        "shortcuts": "Scorciatoie", "focus_duration": "Durata focus",
        "short_break_duration": "Pausa breve", "long_break_duration": "Pausa lunga",
        "long_break_interval": "Intervallo pausa lunga",
        "every_n_pomodoros": "Ogni %d pomodori", "behavior": "Comportamento",
        "auto_start_next": "Avvia automaticamente", "launch_at_login": "Avvia al login",
        "menu_bar_display": "Visualizzazione barra dei menu",
        "display_mode": "Modalità di visualizzazione",
        "time_only": "Solo orario", "time_with_icon": "Orario + Icona",
        "example_time_only": "Esempio: 24:59", "example_time_icon": "Esempio: 🍅 25m",
        "notification_mode": "Modalità notifica",
        "sound_banner": "Audio + Banner", "sound_only": "Solo audio",
        "banner_only": "Solo banner", "off": "Disattivato",
        "sound": "Audio", "tick_enabled": "Ticchettio ultimi 60s",
        "tick_description": "Riproduce un breve ticchettio ogni secondo durante l'ultimo minuto di focus.",
        "tick_sound": "Suono ticchettio", "global_shortcuts": "Scorciatoie globali",
        "shortcut_toggle": "Avvia / Pausa", "shortcut_skip": "Salta",
        "shortcut_reset": "Ripristina",
        "accessibility_hint": "Le scorciatoie globali richiedono il permesso Accessibilità. Concedilo in Impostazioni di Sistema → Privacy e Sicurezza → Accessibilità.",
        "preferences_title": "Preferenze PomodoroNotch",
        "language": "Lingua",
        "language_hint": "Le modifiche hanno effetto immediato.",
        "mon": "Lun", "tue": "Mar", "wed": "Mer", "thu": "Gio", "fri": "Ven", "sat": "Sab", "sun": "Dom",
        "about": "Informazioni",
    ]

    /// Spanish
    static let es: [String: String] = [
        "preferences": "Preferencias", "quit": "Salir", "ready": "Listo",
        "focus_round": "Enfoque · Pomodoro n.° %d",
        "short_break": "Descanso corto", "long_break": "Descanso largo",
        "focus_paused": "Enfoque pausado", "break_paused": "Descanso pausado",
        "start": "Iniciar", "continue": "Continuar", "pause": "Pausa", "skip": "Saltar",
        "today": "Hoy", "pomodoros_count": "%d pomodoros",
        "total_focus": "Enfoque total", "seconds_unit": "s", "minutes_unit": "min",
        "focus_complete_title": "¡Enfoque completado!",
        "focus_complete_body": "¡Buen trabajo! Toma un descanso.",
        "break_complete_title": "Descanso terminado",
        "break_complete_body": "¿Listo para concentrarte de nuevo?",
        "timer": "Temporizador", "appearance": "Apariencia",
        "notifications": "Notificaciones", "shortcuts": "Atajos",
        "focus_duration": "Duración de enfoque",
        "short_break_duration": "Descanso corto", "long_break_duration": "Descanso largo",
        "long_break_interval": "Intervalo de descanso largo",
        "every_n_pomodoros": "Cada %d pomodoros", "behavior": "Comportamiento",
        "auto_start_next": "Iniciar siguiente fase automáticamente",
        "launch_at_login": "Iniciar al iniciar sesión",
        "menu_bar_display": "Visualización en barra de menú",
        "display_mode": "Modo de visualización",
        "time_only": "Solo tiempo", "time_with_icon": "Tiempo + Icono",
        "example_time_only": "Ejemplo: 24:59", "example_time_icon": "Ejemplo: 🍅 25m",
        "notification_mode": "Modo de notificación",
        "sound_banner": "Sonido + Banner", "sound_only": "Solo sonido",
        "banner_only": "Solo banner", "off": "Apagado",
        "sound": "Sonido", "tick_enabled": "Tic-tac últimos 60s",
        "tick_description": "Reproduce un tic-tac corto cada segundo durante el último minuto de enfoque.",
        "tick_sound": "Sonido de tic-tac", "global_shortcuts": "Atajos globales",
        "shortcut_toggle": "Iniciar / Pausa", "shortcut_skip": "Saltar",
        "shortcut_reset": "Restablecer",
        "accessibility_hint": "Los atajos globales requieren permiso de Accesibilidad. Concédelo en Configuración del Sistema → Privacidad y Seguridad → Accesibilidad.",
        "preferences_title": "Preferencias de PomodoroNotch",
        "language": "Idioma",
        "language_hint": "Los cambios surten efecto inmediato.",
        "mon": "Lun", "tue": "Mar", "wed": "Mié", "thu": "Jue", "fri": "Vie", "sat": "Sáb", "sun": "Dom",
        "about": "Acerca de",
    ]

    /// Portuguese
    static let pt: [String: String] = [
        "preferences": "Preferências", "quit": "Sair", "ready": "Pronto",
        "focus_round": "Foco · Pomodoro n.º %d",
        "short_break": "Pausa curta", "long_break": "Pausa longa",
        "focus_paused": "Foco pausado", "break_paused": "Pausa pausada",
        "start": "Iniciar", "continue": "Continuar", "pause": "Pausa", "skip": "Pular",
        "today": "Hoje", "pomodoros_count": "%d pomodoros",
        "total_focus": "Foco total", "seconds_unit": "s", "minutes_unit": "min",
        "focus_complete_title": "Foco concluído!",
        "focus_complete_body": "Bom trabalho! Faça uma pausa.",
        "break_complete_title": "Pausa encerrada",
        "break_complete_body": "Pronto para focar novamente?",
        "timer": "Temporizador", "appearance": "Aparência",
        "notifications": "Notificações", "shortcuts": "Atalhos",
        "focus_duration": "Duração do foco",
        "short_break_duration": "Pausa curta", "long_break_duration": "Pausa longa",
        "long_break_interval": "Intervalo de pausa longa",
        "every_n_pomodoros": "A cada %d pomodoros", "behavior": "Comportamento",
        "auto_start_next": "Iniciar próxima fase automaticamente",
        "launch_at_login": "Iniciar ao fazer login",
        "menu_bar_display": "Exibição na barra de menu",
        "display_mode": "Modo de exibição",
        "time_only": "Apenas tempo", "time_with_icon": "Tempo + Ícone",
        "example_time_only": "Exemplo: 24:59", "example_time_icon": "Exemplo: 🍅 25m",
        "notification_mode": "Modo de notificação",
        "sound_banner": "Som + Banner", "sound_only": "Apenas som",
        "banner_only": "Apenas banner", "off": "Desligado",
        "sound": "Som", "tick_enabled": "Tique-taque últimos 60s",
        "tick_description": "Reproduz um tique-taque curto a cada segundo durante o último minuto de foco.",
        "tick_sound": "Som de tique-taque", "global_shortcuts": "Atalhos globais",
        "shortcut_toggle": "Iniciar / Pausa", "shortcut_skip": "Pular",
        "shortcut_reset": "Redefinir",
        "accessibility_hint": "Atalhos globais exigem permissão de Acessibilidade. Conceda em Ajustes do Sistema → Privacidade e Segurança → Acessibilidade.",
        "preferences_title": "Preferências do PomodoroNotch",
        "language": "Idioma",
        "language_hint": "As alterações têm efeito imediato.",
        "mon": "Seg", "tue": "Ter", "wed": "Qua", "thu": "Qui", "fri": "Sex", "sat": "Sáb", "sun": "Dom",
        "about": "Sobre",
    ]

    /// Indonesian
    static let id: [String: String] = [
        "preferences": "Preferensi", "quit": "Keluar", "ready": "Siap",
        "focus_round": "Fokus · Pomodoro ke-%d",
        "short_break": "Istirahat Singkat", "long_break": "Istirahat Panjang",
        "focus_paused": "Fokus Dijeda", "break_paused": "Istirahat Dijeda",
        "start": "Mulai", "continue": "Lanjutkan", "pause": "Jeda", "skip": "Lewati",
        "today": "Hari Ini", "pomodoros_count": "%d pomodoro",
        "total_focus": "Total Fokus", "seconds_unit": "dtk", "minutes_unit": "mnt",
        "focus_complete_title": "Fokus Selesai!",
        "focus_complete_body": "Kerja bagus! Istirahatlah.",
        "break_complete_title": "Istirahat Selesai",
        "break_complete_body": "Siap fokus lagi?",
        "timer": "Timer", "appearance": "Tampilan",
        "notifications": "Notifikasi", "shortcuts": "Pintasan",
        "focus_duration": "Durasi Fokus",
        "short_break_duration": "Istirahat Singkat", "long_break_duration": "Istirahat Panjang",
        "long_break_interval": "Interval Istirahat Panjang",
        "every_n_pomodoros": "Setiap %d pomodoro", "behavior": "Perilaku",
        "auto_start_next": "Mulai otomatis fase berikutnya",
        "launch_at_login": "Jalankan saat Login",
        "menu_bar_display": "Tampilan Menu Bar",
        "display_mode": "Mode Tampilan",
        "time_only": "Hanya Waktu", "time_with_icon": "Waktu + Ikon",
        "example_time_only": "Contoh: 24:59", "example_time_icon": "Contoh: 🍅 25m",
        "notification_mode": "Mode Notifikasi",
        "sound_banner": "Suara + Spanduk", "sound_only": "Hanya Suara",
        "banner_only": "Hanya Spanduk", "off": "Mati",
        "sound": "Suara", "tick_enabled": "Suara Tik 60 Detik Terakhir",
        "tick_description": "Memutar suara tik pendek setiap detik selama menit terakhir fokus.",
        "tick_sound": "Suara Tik", "global_shortcuts": "Pintasan Global",
        "shortcut_toggle": "Mulai / Jeda", "shortcut_skip": "Lewati",
        "shortcut_reset": "Atur Ulang",
        "accessibility_hint": "Pintasan global memerlukan izin Aksesibilitas. Berikan di Pengaturan Sistem → Privasi & Keamanan → Aksesibilitas.",
        "preferences_title": "Preferensi PomodoroNotch",
        "language": "Bahasa",
        "language_hint": "Perubahan langsung berlaku.",
        "mon": "Sen", "tue": "Sel", "wed": "Rab", "thu": "Kam", "fri": "Jum", "sat": "Sab", "sun": "Min",
        "about": "Tentang",
    ]

    /// Russian
    static let ru: [String: String] = [
        "preferences": "Настройки", "quit": "Выход", "ready": "Готов",
        "focus_round": "Фокус · Помидор №%d",
        "short_break": "Короткий перерыв", "long_break": "Длинный перерыв",
        "focus_paused": "Фокус на паузе", "break_paused": "Перерыв на паузе",
        "start": "Старт", "continue": "Продолжить", "pause": "Пауза", "skip": "Пропустить",
        "today": "Сегодня", "pomodoros_count": "%d помидоров",
        "total_focus": "Общий фокус", "seconds_unit": "с", "minutes_unit": "мин",
        "focus_complete_title": "Фокус завершён!",
        "focus_complete_body": "Отличная работа! Отдохните.",
        "break_complete_title": "Перерыв окончен",
        "break_complete_body": "Готовы снова сосредоточиться?",
        "timer": "Таймер", "appearance": "Оформление",
        "notifications": "Уведомления", "shortcuts": "Горячие клавиши",
        "focus_duration": "Длительность фокуса",
        "short_break_duration": "Короткий перерыв", "long_break_duration": "Длинный перерыв",
        "long_break_interval": "Интервал длинного перерыва",
        "every_n_pomodoros": "Каждые %d помидоров", "behavior": "Поведение",
        "auto_start_next": "Авто-старт следующей фазы",
        "launch_at_login": "Запускать при входе",
        "menu_bar_display": "Отображение в строке меню",
        "display_mode": "Режим отображения",
        "time_only": "Только время", "time_with_icon": "Время + Иконка",
        "example_time_only": "Пример: 24:59", "example_time_icon": "Пример: 🍅 25m",
        "notification_mode": "Режим уведомлений",
        "sound_banner": "Звук + Баннер", "sound_only": "Только звук",
        "banner_only": "Только баннер", "off": "Выкл",
        "sound": "Звук", "tick_enabled": "Тиканье последние 60с",
        "tick_description": "Воспроизводит короткое тиканье каждую секунду в последнюю минуту фокуса.",
        "tick_sound": "Звук тиканья", "global_shortcuts": "Глобальные горячие клавиши",
        "shortcut_toggle": "Старт / Пауза", "shortcut_skip": "Пропустить",
        "shortcut_reset": "Сброс",
        "accessibility_hint": "Для глобальных горячих клавиш требуется разрешение Универсального доступа. Предоставьте его в Системные настройки → Конфиденциальность и безопасность → Универсальный доступ.",
        "preferences_title": "Настройки PomodoroNotch",
        "language": "Язык",
        "language_hint": "Изменения вступают в силу немедленно.",
        "mon": "Пн", "tue": "Вт", "wed": "Ср", "thu": "Чт", "fri": "Пт", "sat": "Сб", "sun": "Вс",
        "about": "О программе",
    ]
}
